### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by olorton** [phpoxford/spires-irc#1]
Obviously open source, but which?

**Comment by ascii-soup** [comment]
For this library, I'm wondering if we should go with something like "Feel free to use it in open source software but not commercial software." - my knowledge of licenses is pretty thin, so does anyone know what that type of license might be?

**Comment by olorton** [comment]
When it comes to FOSS licenses I'm more of a fan of:
- Non-infectious (i.e. not GPL)
- Allows commercial use

The reason for this is with both of these, there can be ambiguity, people get confused by these things. I'd rather others used our stuff and we don't need to worry about people breaching the license agreement.

I'd be interested to hear arguments against this though. I don't actually care about the licensee, I just don't like using other people's code if I cannot work out if I am breaching the license or not.

**Comment by martindilling** [comment]
I usually go with https://opensource.org/licenses/MIT, mostly because it's open for whatever and it's very easy to understand ;)

**Comment by liquorvicar** [comment]
Would be happy to go with MIT although do we want to keep some kind of attribution in case of any derived projects/forks etc? (Or is that what @olorton calls "infectious"?)

**Comment by garethellis36** [comment]
Happy to go with whatever.

**Comment by olorton** [comment]
@liquorvicar MIT is attribution friendly. See http://choosealicense.com/

> The MIT License is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable.

I suggest we also agree on if, what, or how we want to include the (c) notice.
- Do we just want (c) in the lisence file?
- Or just the license and some/all documentation?
- Do we want it in every .php file we create e.g.

```
    <?php

    /**
     * Copyright (c) 2016 The PHP Oxford User Group (github.com/phpoxford/spires)
     * License: MIT (github.com/phpoxford/spires/LICENSE.md)
     */
```

**Comment by ascii-soup** [comment]
It's probably a good idea to include both a LICENSE file and include it in each file header.
It's probably worth us adding a guide on proper attribution (something people can copy/paste to attribute)

**Comment by olorton** [comment]
+1 @ascii-soup let's do both, where should we document the proper attribution, in the readme, contributing, both, or elsewhere?

**Comment by olorton** [comment]
Is everyone happy with this, my PR is prepared.
