### ISSUE TITLE
Set-up Scrutinizer

### ISSUE THREAD

**Issue by garethellis36** [phpoxford/spires-irc#7]

**Comment by martindilling** [comment]
Does Scrutinizer even support PHP7 yet? Didn't think about that yesterday xD

**Comment by liquorvicar** [comment]
Yes, according to the docs (https://scrutinizer-ci.com/docs/configuration/build):

> Pre-installed runtimes:
> 
> 5.4.41, 5.5.25, 5.6.9, 5.6.16, 7.0.0 and hhvm

**Comment by garethellis36** [comment]
Done
